### ISSUE TITLE
How to set rating?

### ISSUE THREAD

**Issue by NicoHood** [getgrav/grav-plugin-star-ratings#17]
Hi,
I am new to grav and I want to add a review option to my site. I found this plugin, but I am wondering, where to set the actual star rating? I guess the twig template with the id is used to **display** it, but where to I **set or store** the ratings?

**Comment by rhukster** [comment]
The twig `stars()` function outputs the current start ratings, and it should be able to take a new rating (assuming you have not already voted, and the spam protection is disabled), via clicking on the stars and it makes an ajax call to store/save the rating.

if you want to test functionality its best to disable the `unique_ip_check` and `disable_after_rate` options, so you can rate multiple times from the same location.  Note you should enable these again on your live site or your results will be easily tampered with.

If you are talking about manually editing the counts, then you need to use a sqlite database editor to edit the db file in the `user/data/star-ratings` folder

**Comment by NicoHood** [comment]
Now I understand. I thought that there is another way to set a rating. The rating is stores inside a json, no sqlite though.
