### ISSUE TITLE
array_key_exists() expects parameter 2 to be array, null given

### ISSUE THREAD

**Issue by adamgajzlerowicz** [getgrav/grav-plugin-star-ratings#2]
I am trying to use the plugin, but I am getting this error:
Twig_Error_Runtime
COPY
An exception has been thrown during the rendering of a template ("array_key_exists() expects parameter 2 to be array, null given") in "default.html.twig" at line 9.

please see the attachment.

![error](https://cloud.githubusercontent.com/assets/675615/15220777/a0369128-1860-11e6-9847-e028fd1a2b34.png)

**Comment by rhukster** [comment]
I've just pushed a new release that should fix this.  Look for v1.0.2 in about 15 mins or so.

**Comment by adamgajzlerowicz** [comment]
Thank you for the update.
 Now the login seems to be loading, but the javascript function is undefined

![screenshot-2](https://cloud.githubusercontent.com/assets/675615/15229988/672fe5f2-188b-11e6-8817-d03c50eeaba5.png)

**Comment by rhukster** [comment]
It appears Grav is already loading the latest jquery-2.x version, then the star-ratings.js runs, then your theme is loading another jquery (probably older).  

i would suggest removing that jquery explicitly loaded by the theme.

**Comment by adamgajzlerowicz** [comment]
You were right, Removing other installation of jQuery fixed the issue. Unfortunately there is another one:

When plugin tries to submit the data if fails. In the dev console  I can see that it tries to open 

`query-2.x.min.js:4 POST http://localhost/blog/star-ratings.json/nonce:6061864bbd08e22dea2371636413e5c4 500 (Internal Server Error)l.cors.b.crossDomain.send @ jquery-2.x.min.js:4n.extend.ajax @ jquery-2.x.min.js:4n.(anonymous function) @ jquery-2.x.min.js:4jQuery.extend.callback @ star-ratings.js:7e.executeCallback @ jquery.star-rating-svg.min.js:1e.applyRating @ jquery.star-rating-svg.min.js:1n.event.dispatch @ jquery-2.x.min.js:3r.handle @ jquery-2.x.min.js:3
star-ratings.js:12 fail`

Then in the response there is a sever 500 error:

`{"error":{"type":"RuntimeException","message":"Page Not Found","file":"\/var\/www\/html\/blog\/system\/src\/Grav\/Common\/Grav.php","line":177}}`

**Comment by rhukster** [comment]
Maybe create a new issue for this, it's kinda far from the `array_key_exists()` error.
