### ISSUE TITLE
Display on blog (article list) page ?

### ISSUE THREAD

**Issue by JibsouX** [getgrav/grav-plugin-star-ratings#4]
I have not test it for that (front actually in dev') so : is the plugin can display on the blog page (article list) for each article the rating ?
If yes, is ti possible to say to the plugin "Show only rating number (ex : 5/10) and no star at all" ?

Thanks in advance !

**Comment by rhukster** [comment]
The plugin just displays the ratings.  There is no logic happening based on that.  Feel free to fork the plugin and modify to your needs though.

**Comment by rhukster** [comment]
I've actually added a new `star_data()` Twig function for the next release that will allow you to get the score and votes count and display them.
