### ISSUE TITLE
Activating show count hover bug

### ISSUE THREAD

**Issue by contentkraft** [getgrav/grav-plugin-star-ratings#5]
I just installed the star ratings plug-in and noticed that it works fine unless I activate the option **show count**. When I do, the hover doesn't work correctly. You have to be one 1.5 stars to the left with your mouse, meaning that you can't give a rating lower than 1.5.

I made a screen recording to show what I mean.

https://vid.me/8LGZ

**Comment by arscar** [comment]
I have same problem. When I activate show count function, the star rating does not work corretly.
I selected 2.5 stars according to the mouse. It shows, I selected 4 stars.  After the click it stored 4.
![star rating](https://cloud.githubusercontent.com/assets/9636691/26784095/04fa153a-49fc-11e7-9043-6c7b75a27836.png)

**Comment by rhukster** [comment]
Check your XHR calls in developer console. I think you will find you have already voted. You can turn that feature off in the plugin settings.

**Comment by arscar** [comment]
I checked it rating: "4". I can solve somehow with little modification plugins (php and css).

**Comment by dynobo** [comment]
@arscar Could you share your solution? I have the same issue...

**Comment by w00fz** [comment]
This is fixed now.

Thanks!
