### ISSUE TITLE
Stars in Google

### ISSUE THREAD

**Issue by Susanne-1920** [getgrav/grav-plugin-star-ratings#6]
Hello,

has anyone managed to bring the stars to google. It seems as google does not see the stars on my side. Only the amount of ratings can be added. 

Thanks
Susanne

**Comment by flaviocopes** [comment]
If you mean the schema.org ratings for products, the plugin does not provide this functionality (yet).

**Comment by Susanne-1920** [comment]
Yes - for products and pages. They call it "Rich Snippets" at Google. Have you any idea how I can do this? I looked for a special tool for get grav and only found this one.

**Comment by flaviocopes** [comment]
This is a widget that allows the user to assign a rating to an item, and return the mean value. Marking as enhancement, but I'm not sure this can be done in the plugin alone, it will need a theme that defines a page template which outputs the data in a certain format.

**Comment by timbo-lino** [comment]
This would be awesome, if you could add this feature. 

I dont think this is too difficult. You just need to add some code to the template.

Maybe you can do something like this.

```
<script type="application/ld+json">
{ "@context": "http://schema.org/",
  "@type": "Blog",
  "name": "{% if header.title %}{{ header.title }}{% endif %}",
  "aggregateRating":
    {"@type": "AggregateRating",
     "ratingValue": "{your:plugin:rating-value}",
     "bestRating": "{your:plugin:total-stars}",
     "ratingCount": "{your:plugin:rating-count}"
    }
}
</script>
```

**Comment by w00fz** [comment]
Thanks @timbo-lino that was a great suggestion that is now implemented.
Would be nice if you could give it a try.

More details on the implementation can be found in the [README](https://github.com/getgrav/grav-plugin-star-ratings#aggregate-rating)
