### ISSUE TITLE
'element.starRating' is undefined

### ISSUE THREAD

**Issue by erdinctogulga** [getgrav/grav-plugin-star-ratings#8]
Hello,
I added the plugin into grav but no star-rating appear in page :/ I checked in developer console and getting the undefined error. I used this plugin before on a different theme and it works well.. I'am stuck at this point can't figure it out. I guess the problem on linking or maybe happen in multiple languages

please check on this page > 
http://hadipisir.com/en/recipes/breakfast_brunch/dutch_baby

**Comment by rhukster** [comment]
Hmm.. Yes definitely looks odd.  I need to double check this plugin and test it with the current JQuery library.  I've not looked at it in a while, so could of broken something.

**Comment by erdinctogulga** [comment]
:) I'll be waiting for the update then thanks.

**Comment by rhukster** [comment]
I just tested on my local with latest Grav version and it's still working fine for me. Passing it over to my @w00fz to see if he has any insight...

**Comment by erdinctogulga** [comment]
..any update on the way?

**Comment by w00fz** [comment]
Is this still an issue @erdinctogulga ? Sorry for being this late, I checked your site but I think you removed that specific page.
It sounds like the js that loads the star ratings script is not loading for you, although I cannot reproduce this on my local.

Can you make sure your `jQuery`, `jquery.star-rating-svg.min.js` and `star-ratings.js` are loading for you?

Thanks

**Comment by erdinctogulga** [comment]
Hi @w00fz,

yes the issue still there :) and never mind for the latency. ;) the star rating is active but still no rating stars shown. https://hadipisir.com/tr/receteler/pilavlar/yaban-mantarli-risotto-tarifi the star rating is below the breadcrumbs... thanks

**Comment by w00fz** [comment]
Hey there @erdinctogulga,
it looks like in your site jQuery is getting loaded twice. The second one is at the very bottom and is basically breaking the starRating jQuery extension.

```
<script src="/user/themes/clean-blog/vendor/jquery/jquery.min.js" type="text/javascript" ></script>
--
  | <script src="/user/themes/clean-blog/vendor/bootstrap/js/bootstrap.min.js" type="text/javascript" ></script>
  | <script src="/user/themes/clean-blog/js/clean-blog.min.js" type="text/javascript" ></script>
  | <script src="/user/themes/clean-blog/vendor/plyr/js/plyr.min.js" type="text/javascript" ></script>
  | <script src="/user/themes/clean-blog/vendor/plyr/js/dd.js" type="text/javascript" ></script>
```

I think it's your theme doing so, if there is an option to disable the jQuery loading from the theme you should try doing that. If it's your own theme, try disabling the loading of jQuery from the twig.

Hope this helps.

**Comment by erdinctogulga** [comment]
thanks 👍  @w00fz :) let me check the js

**Comment by erdinctogulga** [comment]
working nicely 👍

**Comment by w00fz** [comment]
Glad to hear! 👍
